sudo: required
services:
  - docker

before_install:
  - docker build -t learn-kubernetes -f Dockerfile.dev .

script:
  - docker run learn-kubernetes npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "change-this"
  env: "elasticbeanstalk-env"
  bucket_name: "s3-bucket-name"
  bucket_path: "bucket-path"
  on:
    branch: master
